main:
    params: [args]
    steps:
        - init:
            assign:
            - state_id: $${args.id}
            - state_name: $${args.name}
        - getDistricts:
            try:
                call: http.get
                args:
                    url: $${"${cloud_run_url}/states/"+state_id+"/districts"}
                    auth:
                        type: OIDC
                result: districts
            retry:
                max_retries: 8
                backoff:
                    initial_delay: 1
                    max_delay: 60
                    multiplier: 2
        - logStepDistrictsLoaded:
            call: sys.log
            args:
                text: $${"Loaded districts "+ json.encode_to_string(districts.body) }
                severity: INFO 
        - loopDistricts:
            for:
                value: district
                in: $${districts.body}
                steps:
                    - logStepDistrict:
                        call: sys.log
                        args:
                            text: $${"Processing district "+district.name+" of state "+state_name}
                            severity: INFO 
                    - getMandals:
                        try:
                            call: http.get
                            args:
                                url: $${"${cloud_run_url}/states/"+state_id+"/districts/"+district.id+"/mandals"}
                                auth:
                                    type: OIDC
                            result: mandals
                        retry:
                            max_retries: 8
                            backoff:
                                initial_delay: 1
                                max_delay: 60
                                multiplier: 2
                    - logStepMandalsLoaded:
                        call: sys.log
                        args:
                            text: $${"Loaded mandals "+ json.encode_to_string(mandals.body) }
                            severity: INFO 
                    - loopMandals:
                        for:
                            value: mandal
                            in: $${mandals.body}
                            steps:
                                - logStepMandal:
                                    call: sys.log
                                    args:
                                        text: $${"Processing mandal "+mandal.name+" of district "+district.name+" of state "+state_name}
                                        severity: INFO 
                                - getVillages:
                                    try:
                                        call: http.get
                                        args:
                                            url: $${"${cloud_run_url}/states/"+state_id+"/districts/"+district.id+"/mandals/"+mandal.id+"/villages"}
                                            auth:
                                                type: OIDC
                                        result: villages
                                    retry:
                                        max_retries: 8
                                        backoff:
                                            initial_delay: 1
                                            max_delay: 60
                                            multiplier: 2
                                - logStepVillagesLoaded:
                                    call: sys.log
                                    args:
                                        text: $${"Loaded villages "+ json.encode_to_string(villages.body) }
                                        severity: INFO 
                                - downloadCards:
                                    call: experimental.executions.map
                                    args:
                                        workflow_id: shc-scraping-village
                                        arguments: $${villages.body}
                                    result: result