main:
    steps:
        - getStates:
            try:
                call: http.get
                args:
                    url: $${"${cloud_run_url}/states"}
                    auth:
                        type: OIDC
                result: states
            retry:
                max_retries: 8
                backoff:
                    initial_delay: 1
                    max_delay: 60
                    multiplier: 2
        - delegateStates:
            call: experimental.executions.map
            args:
                workflow_id: shc-scraping-states
                arguments: $${states.body}
