main:
    params: [args]
    steps:
        - log1:
            call: sys.log
            args:
                text: $${"Loading card "+json.encode_to_string(args)}
                severity: INFO 
        - downloadCard:
            try:
                call: http.post
                args:
                    url: $${"${cloud_run_url}/download"}
                    auth:
                        type: OIDC
                    body:
                        sample: $${args.sample}
                        village_grid: $${args.village_grid}
                        sr_no: $${args.sr_no}
                        state_id: $${args.state_id}
                        district: $${args.district}
                        district_id: $${args.district_id}
                        mandal: $${args.mandal}
                        mandal_id: $${args.mandal_id}
                        village: $${args.village}
                        village_id: $${args.village_id}
                result: cards
            retry:
                max_retries: 3
                backoff:
                    initial_delay: 1
                    max_delay: 10
                    multiplier: 2
        - log2:
            call: sys.log
            args:
                text: $${"Result "+ cards.body }