main:
    params: [args]
    steps:
        - log1:
            call: sys.log
            args:
                text: $${"Loading card "+json.encode_to_string(args)}
                severity: INFO
        - getCards:
            try:
                call: http.get
                args:
                    url: $${"${cloud_run_url}/states/"+args.state_id+"/districts/"+args.district_id+"/mandals/"+args.mandal_id+"/villages/"+args.id+"/cards?publishable=true"}
                    auth:
                        type: OIDC
                result: cards
            retry:
                max_retries: 8
                backoff:
                    initial_delay: 1
                    max_delay: 60
                    multiplier: 2
        - log2:
            call: sys.log
            args:
                text: $${"Loaded "+string(len(cards.body))+ " cards"}
                severity: INFO        
        - checkCardSize:
            switch:
            - condition: $${0 < len(cards.body)}
              steps:
                - loopCards:
                    for:
                        value: card
                        in: $${cards.body}
                        steps:  
                            - publish_message_to_topic:
                                call: googleapis.pubsub.v1.projects.topics.publish
                                args:
                                    topic: ${pubsub_topic}
                                    body:
                                        messages: 
                                          - data: $${card.data}